### ISSUE TITLE
Fail fast if AWS_S3_BUCKET_NAME isn't set

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#154]
I think we should prevent the Asset Manager app from starting if the `AWS_S3_BUCKET_NAME` environment variable is missing. We're committed to uploading assets to S3 and so I'd like to be alerted as early as possible if something is going to prevent that from happening.

**Comment by chrisroos** [comment]
I think this is dependent on PR #155.

**Comment by floehopper** [comment]
I've replaced #159 with #167, because at this stage I think we only need to be concerned about ensuring the bucket name is set in the Rails production environment (which I believe includes the GOV.UK integration and staging stacks).

Until we make proxying to S3 the default, I don't think there's any need to be so strict in the development environment - I think it's fine to continue using the "null object" version of `S3Storage` so that uploading is a "no-op". And in any case we already have #155 to make us think about that.
