### ISSUE TITLE
Consider fixing or removing the private Asset Manager host alias & associated functionality

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#156]
* [This pull request][1] (in combination with [this follow-up PR][2]) suggests the intention was for the Asset Manager application to be proxied via two different nginx vhosts:
  * `asset-manager.*`
  * `private-asset-manager.*`
* Requests via the `private-asset-manager` vhost require authentication via SSO and that the user is authorized to use the Asset Manager app (via [`GDS::SSO::ControllerMethods#require_signin_permission!`][3]).
* The private vhost is [configured as a vhost alias by Puppet][4].
* The `PRIVATE_ASSET_MANAGER_HOST` environment variable is [provided to the Asset Manager app by Puppet][5].
[This commit note][6] suggests that the intention was for the Asset Manager app to be the only app to know about the environment variable, because it hands out the asset URLs from its API.
* However, the host for the URLs returned by the Asset Manager API is [obtained from `Plek#asset_root`][7] whether or not the asset is marked as `access_limited`.
* If an asset is marked as `access_limited` the Asset Manager tries to check the user's organisation matches that of the asset.
  * **Non-private requests:**
    * The user will *not* be forced to sign in.
    * The authorization check will *not* happen, i.e. any SSO user will work.
    * Only allows access if the user is *already* signed in to SSO and their organisation matches that of the asset.
  * **Private requests:**
    * The user will be forced to sign in.
    * The SSO user must be authorized to access Asset Manager app.
    * Allows access if the user's organisation matches that of the asset.
* Note that `PRIVATE_ASSET_MANAGER_HOST` is set to `private-asset-manager.integration.publishing.service.gov.uk` in integration (see `/etc/govuk/asset-manager/env.d/PRIVATE_ASSET_MANAGER_HOST`) and while `asset-manager.integration.publishing.service.gov.uk` resolves to `backend-internal-lb.backend.integration.publishing.service.gov.uk` (via `/etc/hosts`), `private-asset-manager.integration.publishing.service.gov.uk` doesn't seem to resolve to anything. So it's not obvious to me that using this private hostname from a publishing app would actually work (e.g. the Manuals Publisher app runs on the same backend machine(s) in integration).

We should either make this work or remove the relevant functionality & configuration. Note that all my investigation so far has been by *reading code* and not by experimenting , e.g. on the developer VM.

[1]: https://github.com/alphagov/asset-manager/pull/23
[2]: https://github.com/alphagov/asset-manager/pull/24
[3]: https://github.com/alphagov/gds-sso/blob/9478045b27fd2aa9b2832c7d3df266eea43dab47/lib/gds-sso/controller_methods.rb#L39-L43
[4]: https://github.com/alphagov/govuk-puppet/blob/20a04036d1775e9746a749ca93e6b1d6edb37274/modules/govuk/manifests/apps/asset_manager.pp#L75
[5]: https://github.com/alphagov/govuk-puppet/blob/20a04036d1775e9746a749ca93e6b1d6edb37274/modules/govuk/manifests/apps/asset_manager.pp#L59-L64
[6]: https://github.com/alphagov/govuk-puppet/commit/a3aeba177b161ddb1ad5b09f5421e778d68d9878
[7]: https://github.com/alphagov/asset-manager/blob/543ed6a3cbd9b2a2b3101aec0fc336aaf307faf1/app/presenters/asset_presenter.rb#L15

**Comment by floehopper** [comment]
This may be related to [Investigate whether we can remove the Access Control functionality from Asset Manager](https://github.com/alphagov/asset-manager/issues/99).

**Comment by chrisroos** [comment]
I've just inspected the data in integration and it doesn't look as though we've ever used this access limiting functionality:

```
> Asset.where(access_limited: true).count
0
> Asset.where(:organisation_slug.nin => ['', nil]).count
0
```

We should check this in production too - just in case the data is different for some reason.

**Comment by chrisroos** [comment]
Ruben has just confirmed that both of the commands above return 0 in production too.

I'm going to try to find out whether anyone knows anything about the original requirement but I'm currently thinking/hoping we'll simply be able to remove this unused functionality.

**Comment by chrisroos** [comment]
I've asked about this functionality in Slack:

Chris Roos [2:57 PM] 
Afternoon folks. Does anyone have any knowledge of finders. Specifically about the functionality added to asset-manager 3 1/2 years ago that implements some basic access control for assets - https://github.com/alphagov/asset-manager/pull/23. It appears that it’s never been used so we’re planning to remove it. Please shout if you think this is a bad idea.

Murray Steele [2:58 PM] 
it might be the kind of thing that’s needed by the draft stack?  but maybe it’s never been set up properly

Chris Patuzzo [3:00 PM] 
May be relevant: https://docs.publishing.service.gov.uk/manual/content-preview.html#authentication

[3:01] 
(cc @gpeng)

Chris Roos [3:02 PM] 
That seems to be about Whitehall, @tuzz. The asset-manager app deals with all (I think) assets outside of Whitehall. It looks as though asset-manager had some similar functionality added but that it’s never been used.

Chris Patuzzo [3:02 PM] 
Ahh, I see. That would make sense

Murray Steele [3:03 PM] 
the “finder” work in question might refer to specialist-publisher and specialist documents (and manuals)

[3:03] 
because the different document types available in SP and MP are often called finders

[3:04] 
although I don’t think SP or MP have the notion of access limited like whitehall does

Chris Roos [3:04 PM] 
That’s useful context, thanks @murray.steele!

Murray Steele [3:05 PM] 
but if the intention was to make whitehall use asset-manager at some point then AM would need that sort of functionality

[3:05] 
this might have been step one of going down that path (but never completed)

**Comment by gpeng** [comment]
I'm pretty sure the intention is to move Whitehall to asset-manager in the future so we would require this functionality then. I don't think we do at the moment though and I'm not sure when in 'the future ™️ ' we are going to get to actually doing that.

**Comment by chrisroos** [comment]
Hey @gpeng. We're currently working on moving Whitehall to use Asset Manager so I think we'll probably leave this functionality in place for now so that we can work out whether it's worth repurposing.

**Comment by floehopper** [comment]
This functionality was removed in https://github.com/alphagov/asset-manager/pull/426 and replaced with something similar in https://github.com/alphagov/asset-manager/pull/471 and subsequent related PRs. Closing.
