### ISSUE TITLE
Make explicit decision about response headers from Rails when proxying to S3 via Nginx

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#160]
According to [this email][1], Nginx includes the following response headers from upstream (the Asset Manager Rails app) in the proxied response from S3:

* `Content-Type`
* `Set-Cookie`
* `Content-Disposition`
* `Cache-Control`
* `Expires`
* `Accept-Ranges`

We should make an explicit decision about each of these. In each case, we'll want to

* Does the Rails app ever send this header?
* Should the Rails app ever send this header?
* If it does, are we happy for it to be included in the proxied response?

[1]: https://forum.nginx.org/read.php?2,205636,205665#msg-205665

**Comment by chrisroos** [comment]
I've just checked the values of these headers when making a request to Rails, a request to Rails + proxy to S3, a request to nginx and a request to nginx + proxy to S3.

| Header              | Rails+NFS | Rails+S3 | nginx+NFS | nginx+S3 |
| ------------------- | --------- | -------- | --------- | -------- |
| Content-Type        | Y         | Y        | Y         | Y        |
| Set-Cookie          | N         | N        | N         | N        |
| Content-Disposition | Y         | Y        | Y         | Y        |
| Cache-Control       | Y         | Y        | Y         | Y        |
| Expires             | N         | N        | N         | N        |
| Accept-Ranges       | N         | N        | Y         | Y        |

The `Cache-Control` header is set in Rails for all responses using `set_expiry`.

The `Content-Type` and `Content-Disposition` headers are set in Rails by the call the `sendfile` when serving assets from the filesystem and set explicitly when serving assets from S3.

The `Set-Cookie` header is empty in all cases because we're not setting any cookies in the asset-manager app.

The `Expires` header is empty in all cases. We're using the `Cache-Control` header to send caching information and this header takes precedent over the `Expires` header (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expires).

The `Accept-Ranges` header is evidently being added by nginx as it's not present in our Rails responses. This behaviour is being investigated in issue #161 so I don't think there's anything more to do about it in here.

**Comment by chrisroos** [comment]
I'm happy that I understand the results of the investigation into these headers and that I don't think we need to do anything.

@floehopper / @chrislo : I'm going to close this issue but feel free to reopen if you think we need to investigate further.
