### ISSUE TITLE
Compare response headers in requests served by Whitehall and requests served by Asset Manager

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#220]
We'll want to do this before updating the nginx config to serve Whitehall image assets from Asset Manager (see issue #214).

It might be worth looking at the before & after filters in Whitehall's `ApplicationController` to check whether there's any functionality which we should move over.

**Comment by floehopper** [comment]
## Whitehall image response headers from Whitehall app

```
$ vagrant ssh
$ cd /var/govuk/whitehall

# Create example image
$ convert -size 960x640 canvas:blue blue-960x640.gif

# Run Rails console
$ rails c

# Create instance of ImageData with example file
irb> id = ImageData.create!(file: File.open('blue-960x640.gif'))

# Obtain public path to example image
irb> id.file.url # => "/government/uploads/system/uploads/image_data/file/64083/blue-960x640.gif"

# Wait for /etc/cron.d/run_fake_virus_scan to run (every 1 min)
# Or run the following command:
$ govuk_setenv whitehall bundle exec rake development:fake_virus_scan

# Request the image from the assets-origin host
$ curl -s -v "http://assets-origin.dev.gov.uk/government/uploads/system/uploads/image_data/file/64083/blue-960x640.gif" > /dev/null
*   Trying 10.1.1.254...
* TCP_NODELAY set
* Connected to assets-origin.dev.gov.uk (10.1.1.254) port 80 (#0)
> GET /government/uploads/system/uploads/image_data/file/64083/blue-960x640.gif HTTP/1.1
> Host: assets-origin.dev.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Access-Control-Allow-Headers: origin, authorization
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Origin: *
< Cache-Control: max-age=14400, public
< Connection: close
< Content-Disposition: inline; filename="blue-960x640.gif"
< Content-Length: 1323
< Content-Type: image/gif
< Date: Tue, 26 Sep 2017 11:42:34 GMT
< ETag: "59ca3af2-52b"
< Last-Modified: Tue, 26 Sep 2017 11:33:06 GMT
< Server: nginx
< X-Frame-Options: SAMEORIGIN
<
{ [1323 bytes data]
* Closing connection 0
```

## Whitehall image response headers from Asset Manager app

* Route `assets-origin.dev.gov.uk/government/uploads/` -> static app in `govuk-puppet/hieradata/common.yaml`
* Proxy `static.dev.gov.uk/government/uploads/` to `asset-manager.dev.gov.uk/government/uploads` in `govuk-puppet/modules/govuk/templates/static_extra_nginx_config.conf.erb`
* Enable `ApplicationController#set_expiry` in Asset Manager in development

```
$ vagrant ssh
$ cd /var/govuk/asset-manager

# Create example image
$ convert -size 960x640 canvas:blue blue-960x640.gif

# Upload example image to Asset Manager as Whitehall asset
$ curl http://asset-manager.dev.gov.uk/whitehall_assets --form "asset[file]=@blue-960x640.gif" --form "asset[legacy_url_path]=/government/uploads/system/uploads/image_data/file/64083/blue-960x640.gif"
{"_response_info":{"status":"created"},"id":"http://asset-manager.dev.gov.uk/assets/59ca59f3759b746be1e2cae0","name":"blue-960x640.gif","content_type":"image/gif","file_url":"http://assets-origin.dev.gov.uk/government/uploads/system/uploads/image_data/file/64083/blue-960x640.gif","state":"unscanned"}

# Check that virus scan has completed
$ curl http://asset-manager.dev.gov.uk/assets/59ca59f3759b746be1e2cae0
{"_response_info":{"status":"ok"},"id":"http://asset-manager.dev.gov.uk/assets/59ca59f3759b746be1e2cae0","name":"blue-960x640.gif","content_type":"image/gif","file_url":"http://assets-origin.dev.gov.uk/government/uploads/system/uploads/image_data/file/64083/blue-960x640.gif","state":"clean"}

# Request the image from the assets-origin host
$ curl -v -s http://assets-origin.dev.gov.uk/government/uploads/system/uploads/image_data/file/64083/blue-960x640.gif > /dev/null
*   Trying 10.1.1.254...
* TCP_NODELAY set
* Connected to assets-origin.dev.gov.uk (10.1.1.254) port 80 (#0)
> GET /government/uploads/system/uploads/image_data/file/64083/blue-960x640.gif HTTP/1.1
> Host: assets-origin.dev.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Access-Control-Allow-Headers: origin, authorization
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Origin: *
< Cache-Control: max-age=14400, public
< Connection: close
< Content-Disposition: inline; filename="blue-960x640.gif"
< Content-Length: 1323
< Content-Type: image/gif
< Date: Tue, 26 Sep 2017 15:27:57 GMT
< ETag: "59ca59f3-52b"
< GOVUK-Asset-Manager-File-Store: NFS
< Last-Modified: Tue, 26 Sep 2017 13:45:23 GMT
< Server: nginx
< Strict-Transport-Security: max-age=31536000
<
{ [1323 bytes data]
* Closing connection 0
```

## Differences in response headers (Whitehall vs Asset Manager)

```
11,13c11,14
< Date: Tue, 26 Sep 2017 11:42:34 GMT
< ETag: "59ca3af2-52b"
< Last-Modified: Tue, 26 Sep 2017 11:33:06 GMT
---
> Date: Tue, 26 Sep 2017 15:27:57 GMT
> ETag: "59ca59f3-52b"
> GOVUK-Asset-Manager-File-Store: NFS
> Last-Modified: Tue, 26 Sep 2017 13:45:23 GMT
15c16
< X-Frame-Options: SAMEORIGIN
---
> Strict-Transport-Security: max-age=31536000
```

### Date

The differences in the values of the `Date` header are expected because they reflect the time of the request.

### ETag

As explained in [this asset-manager PR][7], Nginx generates the ETag from a combination of the underlying file's `mtime` (last modified) and its size. Since in the tests above we've uploaded different incarnations of the files, I'd expect the `mtime`s to be different, which explains why the first part of the `ETag` value is different in the two scenarios.

We'll need to work out whether we want to keep this unchanged in order to avoid invalidating all cached assets and, if we do, how do we want to do it.

### GOVUK-Asset-Manager-File-Store

This extra debug header appears in the response from Asset Manager. This shouldn't cause any problems and indeed might prove useful in debugging problems.

### Last-Modified

I think this is basically the same problem as for the `ETag` header.

### X-Frame-Options

This extra header is appears in the response from Whitehall. There is code in `govuk-puppet/modules/govuk/manifests/apps/whitehall.pp` to ["Respect X-Frame-Options from Rails application"][1]. [Rails sets this header to `SAMEORIGIN` by default][2] and the default value is not overridden using `config.action_dispatch.default_headers`.

As explained in [this asset-manager issue][4] we made [these changes to govuk-puppet PR][4] to ensure this header was set to `DENY` for all assets serve by Asset Manager. However, for some reason I'm not seeing `X-Frame-Options: DENY` in the response from Asset Manager; neither for a Whitehall asset nor a Mainstream asset. I'm a bit confused by this, but have decided not to investigate any further for now.

### Strict-Transport-Security

This extra header is appears in the response from Asset Manager. I'm not sure why it doesn't appear in the response from Whitehall. The `/government/uploads` location block in `govuk-puppet/modules/govuk/manifests/apps/whitehall.pp` looks to have [similar code][5] to [the code][6] in the `/government/uploads` location in `govuk-puppet/modules/govuk/templates/static_extra_nginx_config.conf.erb`.

[1]: https://github.com/alphagov/govuk-puppet/blob/65ee389b8cb0b3a64439dd3ced8eb6b0b6a5bc82/modules/govuk/manifests/apps/whitehall.pp#L237-L238
[2]: http://guides.rubyonrails.org/v5.0.4/security.html#default-headers
[3]: https://github.com/alphagov/asset-manager/issues/166
[4]: https://github.com/alphagov/govuk-puppet/pull/6385
[5]: https://github.com/alphagov/govuk-puppet/blob/master/modules/govuk/manifests/apps/whitehall.pp#L246-L248
[6]: https://github.com/alphagov/govuk-puppet/blob/6377629401f1cc9cb9ad79d43e4aed96a5281046/modules/govuk/templates/static_extra_nginx_config.conf.erb#L27-L30
[7]: https://github.com/alphagov/asset-manager/pull/157

**Comment by floehopper** [comment]
I've captured the specific bits of work we might need to do in three new issues: #234, #235 & #236.

**Comment by floehopper** [comment]
#234, #235 & #236 have all been resolved, but I'm going to keep this issue open, because I think we should do a final check of the headers before we switch over to serve Whitehall assets from Asset Manager - as I have discovered it's all too easy to make accidental changes to the response headers when making changes to the Nginx configuration.

Although I'm not going to close the issue, I'm going to un-assign myself, because I'm not planning on working on it for now.

**Comment by floehopper** [comment]
I'm going to close this issue and add a reminder to #214 to check the response headers before we switch over the Nginx configuration.
