### ISSUE TITLE
Add ability to remove Whitehall images from Asset Manager

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#226]
This stems from my investigation in issue #225.

Whitehall allows you to remove previously uploaded images from Consultations (and possibly other types of documents). We'll need to be able to remove Whitehall images from Asset Manager in order to retain this functionality.

Requesting an image that's been removed redirects to the thumbnail-placeholder image in Whitehall.

Removing an image from a Consultation in Whitehall also results in the image being removed from the filesystem. Although Asset Manager allows you to remove images, I _think_ it just marks them as deleted in the database and leaves them on the filesystem. We'll have to decide whether this is good enough behaviour for the Whitehall images.

**Comment by floehopper** [comment]
@chrisroos:

> Removing an image from a Consultation in Whitehall also results in the image being removed from the filesystem. Although Asset Manager allows you to remove images, I _think_ it just marks them as deleted in the database and leaves them on the filesystem. We'll have to decide whether this is good enough behaviour for the Whitehall images.

My assumption is that asset removal works like this for mainstream assets in Asset Manager in order to support the `restore` API endpoint.

**Comment by floehopper** [comment]
As far as I can see, Whitehall should be able to use the existing `ELETE /assets/:id` API endpoint to remove a Whitehall asset as long as it knows the Whitehall asset's ID which is returned in the response from the `POST /whitehall_assets` API endpoint. The implication here is that Whitehall will need to store the asset's ID in its database.

The following shows how I was able to use the existing API endpoints to remove and restore a Whitehall asset:

## Create test file to upload

    $ echo `date` > tmp.txt
    $ cat tmp.txt
    Thu 21 Sep 2017 14:17:56 BST

## Create Whitehall asset to be served at /government/uploads/path/to/tmp.txt

    $ curl http://asset-manager.dev.gov.uk/whitehall_assets --form "asset[file]=@tmp.txt" --form "asset[legacy_url_path]=/government/uploads/path/to/tmp.txt"
    {"_response_info":{"status":"created"},"id":"http://asset-manager.dev.gov.uk/assets/59c3bc3c759b743503c0c66d","name":"tmp.txt","content_type":"text/plain","file_url":"http://assets-origin.dev.gov.uk/government/uploads/path/to/tmp.txt","state":"unscanned"}

## Get status of Whitehall asset (after successful virus scanning)

    $ curl http://asset-manager.dev.gov.uk/assets/59c3bc3c759b743503c0c66d
    {"_response_info":{"status":"ok"},"id":"http://asset-manager.dev.gov.uk/assets/59c3bc3c759b743503c0c66d","name":"tmp.txt","content_type":"text/plain","file_url":"http://assets-origin.dev.gov.uk/government/uploads/path/to/tmp.txt","state":"clean"}

## Request Whitehall asset from public URL path

Note: I've used `asset-manager.dev.gov.uk` vs `assets-origin.dev.gov.uk`, because we haven't yet made the relevant changes to the Nginx configuration to make the latter work.

    $ curl http://asset-manager.dev.gov.uk/government/uploads/path/to/tmp.txt
    Thu 21 Sep 2017 14:17:56 BST

## Delete Whitehall asset (using existing API endpoint)

    $ curl http://asset-manager.dev.gov.uk/assets/59c3bc3c759b743503c0c66d --request DELETE
    {"_response_info":{"status":"success"},"id":"http://asset-manager.dev.gov.uk/assets/59c3bc3c759b743503c0c66d","name":"tmp123.txt","content_type":"text/plain","file_url":"http://assets-origin.dev.gov.uk/government/uploads/path/to/tmp.txt","state":"clean"}

## Whitehall asset status is "not found"

    $ curl http://asset-manager.dev.gov.uk/assets/59c3bc3c759b743503c0c66d
    {"_response_info":{"status":"not found"}}

## Request to public URL path for Whitehall asset responds with 404 Not Found

    $ curl http://asset-manager.dev.gov.uk/government/uploads/path/to/tmp.txt
    {"_response_info":{"status":"not found"}}

## Restore Whitehall asset (using existing API endpoint)

    $ curl http://asset-manager.dev.gov.uk/assets/59c3bc3c759b743503c0c66d/restore --request POST --data ''
    {"_response_info":{"status":"success"},"id":"http://asset-manager.dev.gov.uk/assets/59c3bc3c759b743503c0c66d","name":"tmp123.txt","content_type":"text/plain","file_url":"http://assets-origin.dev.gov.uk/government/uploads/path/to/tmp.txt","state":"clean"}

## Whitehall asset status is "ok"

    $ curl http://asset-manager.dev.gov.uk/assets/59c3bc3c759b743503c0c66d
    {"_response_info":{"status":"ok"},"id":"http://asset-manager.dev.gov.uk/assets/59c3bc3c759b743503c0c66d","name":"tmp123.txt","content_type":"text/plain","file_url":"http://assets-origin.dev.gov.uk/government/uploads/path/to/tmp.txt","state":"clean"}

## Request to public URL path for Whitehall asset responds with content of new file

    $ curl http://asset-manager.dev.gov.uk/government/uploads/path/to/tmp.txt
    Thu 21 Sep 2017 14:23:30 BST

**Comment by floehopper** [comment]
I'm happy for us to re-use the existing API endpoints to remove (and, if necessary, restore) Whitehall assets. Thus I'm going to close this issue.

@chrisroos, @chrislo: Feel free to re-open if you disagree.
