### ISSUE TITLE
Change Asset Manager API to allow replacement of Whitehall assets

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#229]
This stems from my investigation in issue #225.

It turns out that it's possible to replace Whitehall images in a couple of instances (e.g. the images for people). I think this means we'll need to add this same functionality to the Whitehall endpoint in the Asset Manager unless we can think of an alternative approach (possibly by changing Whitehall)?

You can test the current behaviour of replacing an image in Whitehall by:

* Creating a person and uploading an image.
* Making a change to the image locally while ensuring to keep the filename the same.
* Updating the person with the new image.
* Observing that the image URL hasn't changed (i.e. it has the same `<id>` and `<filename>` in the path).

**Comment by floehopper** [comment]
As far as I can see, Whitehall should be able to use the existing `PUT /assets/:id` API endpoint to update a Whitehall asset as long as it knows the Whitehall asset's ID which is returned in the response from the `POST /whitehall_assets` API endpoint. The implication here is that Whitehall will need to store the asset's ID in its database.

Note that since Whitehall specifies the public URL path at which to serve the asset, any change in filename does not affect this public URL path. I think this behaviour makes sense and is what we need in Whitehall.

@chrisroos: Does that sound correct to you? Or do you think we need to be able to update the filename in the public URL path?

The following shows how I was able to use the existing API endpoint to update a Whitehall asset:

## Create test file to upload

    $ echo `date` > tmp.txt
    $ cat tmp.txt
    Thu 21 Sep 2017 14:17:56 BST

## Create Whitehall asset to be served at /government/uploads/path/to/tmp.txt

    $ curl http://asset-manager.dev.gov.uk/whitehall_assets --form "asset[file]=@tmp.txt" --form "asset[legacy_url_path]=/government/uploads/path/to/tmp.txt"
    {"_response_info":{"status":"created"},"id":"http://asset-manager.dev.gov.uk/assets/59c3bc3c759b743503c0c66d","name":"tmp.txt","content_type":"text/plain","file_url":"http://assets-origin.dev.gov.uk/government/uploads/path/to/tmp.txt","state":"unscanned"}

## Get status of Whitehall asset (after successful virus scanning)

    $ curl http://asset-manager.dev.gov.uk/assets/59c3bc3c759b743503c0c66d
    {"_response_info":{"status":"ok"},"id":"http://asset-manager.dev.gov.uk/assets/59c3bc3c759b743503c0c66d","name":"tmp.txt","content_type":"text/plain","file_url":"http://assets-origin.dev.gov.uk/government/uploads/path/to/tmp.txt","state":"clean"}

## Request Whitehall asset from public URL path

Note: I've used `asset-manager.dev.gov.uk` vs `assets-origin.dev.gov.uk`, because we haven't yet made the relevant changes to the Nginx configuration to make the latter work.

    $ curl http://asset-manager.dev.gov.uk/government/uploads/path/to/tmp.txt
    Thu 21 Sep 2017 14:17:56 BST

## Create new test file to replace existing one

    $ echo `date` > tmp123.txt
    $ cat tmp123.txt 
    Thu 21 Sep 2017 14:23:30 BST

## Update Whitehall asset (using existing API endpoint)

    $ curl http://asset-manager.dev.gov.uk/assets/59c3bc3c759b743503c0c66d --request PUT --form "asset[file]=@tmp123.txt" 
    {"_response_info":{"status":"success"},"id":"http://asset-manager.dev.gov.uk/assets/59c3bc3c759b743503c0c66d","name":"tmp123.txt","content_type":"text/plain","file_url":"http://assets-origin.dev.gov.uk/government/uploads/path/to/tmp.txt","state":"unscanned"}

## Request to public URL path for Whitehall asset responds with content of new file

    $ curl http://asset-manager.dev.gov.uk/government/uploads/path/to/tmp.txt
    Thu 21 Sep 2017 14:23:30 BST

**Comment by floehopper** [comment]
I've just realised that one slight odd-ness is that although the "filename" in the public URL path remains the same when you update a Whitehall asset, the filename set in the `Content-Disposition` response header is the new filename. See the following for a demonstration of this:

```
$ curl -s -v http://asset-manager.dev.gov.uk/government/uploads/path/to/tmp.txt
*   Trying 10.1.1.254...
* TCP_NODELAY set
* Connected to asset-manager.dev.gov.uk (10.1.1.254) port 80 (#0)
> GET /government/uploads/path/to/tmp.txt HTTP/1.1
> Host: asset-manager.dev.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 21 Sep 2017 14:18:21 GMT
< Content-Type: text/plain
< Content-Length: 29
< Last-Modified: Thu, 21 Sep 2017 13:25:18 GMT
< Connection: close
< Vary: Accept-Encoding
< Content-Disposition: inline; filename="tmp123.txt"
< Cache-Control: private
< ETag: "59c3bdbe-1d"
< GOVUK-Asset-Manager-File-Store: NFS
< Accept-Ranges: bytes
< 
Thu 21 Sep 2017 14:23:30 BST
* Closing connection 0
```

The public URL path: `/government/uploads/path/to/tmp.txt`
The `Content-Disposition` filename: `tmp123.txt`

@chrisroos, @chrislo: What do you think the correct behaviour should be?

**Comment by floehopper** [comment]
I'm no longer actively working on this, so I'm going to un-assign myself.

**Comment by floehopper** [comment]
This work is almost certainly dependent on (and perhaps even part of) #245, so I'm going to mark it as blocked.

**Comment by chrislo** [comment]
I'm removing the blocked label as I'm working on this alongside #245 as part of #325.
