### ISSUE TITLE
Avoid potential race conditions when creating/deleting Whitehall organisation logos in Asset Manager

### ISSUE THREAD

**Issue by chrisroos** [alphagov/asset-manager#277]
Replacing organisation logos in Whitehall actually triggers a delete and then addition of the existing logo. This works fine when the operations are synchronous (e.g. when deleting from and adding to disk) but introduces a potential race condition when they're asynchronous (i.e. when deleting from and adding to Asset Manager).

Some ideas:

* We store the ID of the Whitehall asset in Asset Manager before the job is queued to actually do the delete. This would ensure we're deleting the correct asset.
* We somehow combine the delete and create operations so that they always happen in the correct order.
* We synchronously delete the old asset before queuing up a job to create the new asset (on the assumption that deleting will be quicker than adding).

**Comment by chrisroos** [comment]
Having thought about this a bit more, I wonder whether there is a problem with our current implementation.

I'd assumed the something like this sequence of events might be possible:

1. Replace an organisation logo in Whitehall with a file of the same name as the original logo
2. A job to remove the old logo is enqueued
3. A job to add the new logo is enqueued
4. The job to remove the old logo fails for some reason (e.g. network timeout)
5. The job to add the new logo runs successfully
6. The job to remove the old logo is retried and succeeds in deleting the newly uploaded logo

However, in this scenario, step 5 can't succeed because of the validation in Asset Manager that requires all `legacy_url_path`s to be unique.

@floehopper / @chrislo: Am I missing something or am I correct in thinking that this isn't actually a problem?

**Comment by floehopper** [comment]
@chrisroos:

While I agree that nothing really "bad" can happen in this scenario, in the extreme if both jobs continue to be retried in the wrong order, the replacement might never complete. I feel a bit uncomfortable with the replacement being split up into two jobs, when really it should be a single job.

Note that there's also another possible race condition scenario:

1. Replace an organisation logo in Whitehall with a file of the same name as the original logo
2. A job to remove the old logo is enqueued
3. A job to add the new logo is enqueued
4. The job to remove the old logo is taken off the queue, but the call to Asset Manager is not made 
5. The job to add the new logo is taken off the queue and the call to Asset Manager is made, but fails due to the uniqueness constraint

Assuming the job to remove the old logo then runs and the job to add the new logo is re-tried, maybe everything will be OK.

**Comment by chrisroos** [comment]
While we think there might be some potential for race conditions around the existing behaviour we don't think it's enough to warrant us investigating further at this point.

We're closing this for now but can always resurrect it if necessary.
