### ISSUE TITLE
One production asset is missing a file on NFS

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#310]
These exceptions relate to an asset (ID: `5a0ae429ed915d0adcdf4731 `) which has been marked as deleted, but has no underlying file on the NFS mount.

* https://sentry.io/govuk/app-asset-manager/issues/407665295/
* https://sentry.io/govuk/app-asset-manager/issues/407665296/

Given that the file is missing, I think we don't have much choice other than to permanently delete the relevant asset, i.e. otherwise it could theoretically be restored and then result in a `404 Not Found`.

**Comment by floehopper** [comment]
@chrisroos, @chrislo: Do you have thoughts on this? The more I think about it, the more I think we should just permanently delete the asset.

**Comment by chrisroos** [comment]
@floehopper: I found a report in Zendesk asking for this file to be removed as it contained sensitive information. Therefore I think it's safe to permanently delete the asset from the Asset Manager database.

**Comment by floehopper** [comment]
@chrisroos: Thanks.

**Comment by floehopper** [comment]
I've opened #311 which I'm hoping to use to resolve this issue.

**Comment by chrisroos** [comment]
@floehopper - I took the liberty of asking in 2ndline to get this file deleted and @danielroseman was good enough to do it for us. I did this because it's not obvious to me that it warranted the code change/review/deployment hassle before then asking someone to delete it for us.

Daniel confirmed that we were deleting the correct asset by comparing the `deleted_at` and `filename` to the values in integration (`2017-11-14 16:30:40 UTC` and `"transcript-hearing-with-campaign-groups-271017.pdf"` respectively) before calling `destroy!` to remove it completely. We then checked that it had been removed by executing `sset.unscoped.find('5a0ae429ed915d0adcdf4731')`, which returned `Document(s) not found for class Asset with id(s) 5a0ae429ed915d0adcdf4731`.

As part of testing the commands to run, I've also deleted this asset in integration.

Is there anything else we should check before marking this as closed?

**Comment by floehopper** [comment]
@chrisroos Thanks for doing this. Assuming Daniel ran those commands in production then I don't think there's anything else to do. The asset will be deleted in staging by the nightly sync and you've already deleted it from integration. I'll close #311 since it's no longer needed and it doesn't actually work correctly for assets which *do* have a corresponding S3 object. I'll also close this issue. Please re-open if Daniel did not run the commands on production.
