### ISSUE TITLE
Query the database at job execution time vs job queue time when updating attributes on Asset Manager assets

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#507]
Currently all the `ServiceListeners::AttachmentXxxxUpdater` classes queue up jobs using the `AssetManagerUpdateAssetWorker` which accepts a `Hash` of attributes which are determined at the time the job is queued up.

If we're going to re-use the logic in these updaters to update the attributes of all existing Whitehall attachment assets in Asset Manager, I think we're going to want to determine the attributes at job execution time. This is because we might be queueing up millions of jobs and it might be a long time before the ones at the back of the queue are executed.

**Comment by chrisroos** [comment]
The attachment listeners/workers have been updated so that we only store an `AttachmentData.id` on the queue and look up the attributes at the time the job is processed:

* [Move AttachmentAccessLimitedUpdater logic to a worker](https://github.com/alphagov/whitehall/pull/3861)
* [Move AttachmentDraftStatusUpdater logic to worker](https://github.com/alphagov/whitehall/pull/3860)
* [Inline attachment link header updater logic into worker](https://github.com/alphagov/whitehall/pull/3856)
* [Extract AttachmentRedirectUrlUpdater logic into worker](https://github.com/alphagov/whitehall/pull/3852)
* [AttachmentReplacementIdUpdater queries required data when job is executed](https://github.com/alphagov/whitehall/pull/3842)
* [Delete assets in Asset Manager when attachments are deleted](https://github.com/alphagov/whitehall/pull/3853)

**Comment by chrisroos** [comment]
I'm not sure it's easy/possible to really validate this is working as expected in production given that it's an internal change. So I'm going to close this issue.

@chrislo / @floehopper: Feel free to re-open it if there's more testing you want to do.
